WeightGameHighScore = 0

HeightGameHighScore = 0


-- Executes the first time the script is loaded
function init(self)
	-- Must aquire input focus to pass that focus on to the collections it loads
	msg.post(".", "acquire_input_focus")
	-- Loads the title screen
	msg.post("#TitleScreen", "load")
end

-- Executes when it receives a message
function on_message(self, message_id, message, sender)
	-- Sent back from the proxy's after they are asked to load
	if message_id == hash("proxy_loaded") then
		-- Tells the sender (proxy which was loaded) to initialize (execute init() code)
		msg.post(sender, "init")
		-- enables the sender
		-- TODO: See If There's A Better Way To Do This
		msg.post(sender, "enable")
	end
	if message_id == hash("load Game Select") then
		-- Sents message to weightGame proxy to load
		msg.post("#GameSelect","load")
		-- Disables TitleScreen
		msg.post("#TitleScreen","disable")
	end
	-- Message sent to load weight game specifically
	if message_id == hash("load Weight Game") then
		-- Sents message to weightGame proxy to load
		msg.post("#WeightGame","load")
		-- Disables TitleScreen
		msg.post("#GameSelect","disable")
	end
	if message_id == hash("load Height Game") then
		-- Sents message to weightGame proxy to load
		msg.post("#HeightGame","load")
		-- Disables TitleScreen
		msg.post("#GameSelect","disable")
	end
end


-- Unused functions, preserved in case they are needed in the future
	
function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
