-- TODO: Make Look Better In General

-- Executes upon first being loaded
function init(self)
	-- Gets Input Focus
	msg.post(".", "acquire_input_focus")
end

-- Executes upon receiving input
function on_input(self, action_id, action)
	-- If the user left clicks, executes once per clickk
	if action_id == hash("LeftClick") and action.pressed then
		-- Prints ackniwledgement for debuggin
		print("Action pressed")
		-- Sends message to loader to load the weight game
		msg.post("Loader:/Loader", "load Game Select")
	end
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
